language: python

# install:
#   #- pip install -r requirements.txt
#   - pip install pytest 
script: python intallingGitHub.py
  #- pytest installingGitHub.py
  #- python [...]
  #- #installingGitHub.py
  