language: python
python:
  -3.7.1
os: windows
cache: yarn

install:
  - yarn intall

script: 
  -yarn test
  -yarn run build

deploy:
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: master

  # this suppose to be working
     


  ''' language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7.1
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
script: pytest # run tests
      : make test
after_success:
  - codecov # submit coverage

  ''''